apiVersion: v1
kind: Service             
metadata:
  name: goplay-lb
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 8080               # 3
    protocol: TCP          # 4
    targetPort: 8080         # 5
  selector:                # 6
    app: goplay       # 7