apiVersion: v1
kind: Pod                                        
metadata:
  name: goplay-2  
  labels:
    app: goplay
spec:                                              
  containers:
    - image: dreadelus/goplay 
      name: goplay                             
      ports:
        - containerPort: 8080                          